### ISSUE TITLE
DFR0654 & plaform.io

### ISSUE THREAD

**Issue by imabot2** [Torxgewinde/Firebeetle-2-ESP32-E#5]
Hi, I'm not sure which board and MCU I have to select to program a [DRF0654 board](https://wiki.dfrobot.com/FireBeetle_Board_ESP32_E_SKU_DFR0654).

I try several configurations, `firebeetle32`, `dfrobot_firebeetle2_esp32s3` with different MCU configuration (`esp32`, `ESP32-E`), but none of then is working properly. 

With the following configuration, I can upload the code, but pinout seems to be wrong. I think this is not the right configuration:

```
board = dfrobot_firebeetle2_esp32s3
board_build.mcu = esp32
```

Any help is welcome.

**Comment by Torxgewinde** [comment]
Hello Fifi,
I cannot say for sure which PlatformIO settings are correct, because I am using the Arduino-IDE. 

The settings in Arduino-IDE are as per this screenshot:
[As in issue #4](https://user-images.githubusercontent.com/12876583/210063434-cd9c5403-7cae-406d-a20f-511611c7f7f6.png)

I would expect PlatformIO to also use ESP32-E as mcu, their [current repository](https://github.com/platformio/platform-espressif32/tree/master/boards) does not seem to include this board (DFR0654, ESP32-E) yet. [I would suggest watching your issue #1002 in the Platformio project](https://github.com/platformio/platform-espressif32/issues/1002), because the issue needs to be fixed there.

Best regards!
